# Week 2: Python Fundamentals and Basic Statistics
Hereâ€™s how you can structure these notes within a Jupyter Notebook to make it organized and easy to understand:

---

```markdown
# Python Libraries for Data Analysis and Visualization

## Pandas
- **Purpose**: Data manipulation and analysis (e.g., CSV processing, handling DataFrames).
- **Key Features**:
  - Easily load and explore datasets (e.g., CSV files).
  - Perform operations like filtering, grouping, and aggregating data.
  - Supports handling missing data efficiently.
  
**Example**:
```python
import pandas as pd
data = pd.read_csv("your_file.csv")
print(data.head())  # Displays the first 5 rows
```

---

## Numpy
- **Purpose**: Numerical computations (e.g., arrays, statistics).
- **Key Features**:
  - Supports multi-dimensional arrays for storing numerical data.
  - Provides functions for fast mathematical computations.
  - Used in conjunction with other libraries like Pandas and Scikit-learn.

**Example**:
```python
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array.mean())  # Outputs the average
```

---

## Seaborn
- **Purpose**: Data visualization (e.g., histograms, scatter plots, correlation matrices).
- **Key Features**:
  - Simplifies the creation of complex visualizations.
  - Allows customization with colors, labels, and annotations.
  - Built on top of Matplotlib for better usability.

**Example**:
```python
import seaborn as sns
import matplotlib.pyplot as plt
sns.histplot([1, 2, 2, 3, 3, 3, 4], bins=4)
plt.show()
```

---

## Matplotlib
- **Purpose**: Basic plotting and graphical representations.
- **Key Features**:
  - Highly customizable for creating unique visualizations.
  - Supports line plots, bar charts, scatter plots, and more.
  - Often used alongside Seaborn for advanced visualizations.

**Example**:
```python
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4], [10, 20, 25, 30])
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Line Plot Example")
plt.show()
```

---

## Statsmodels
- **Purpose**: Statistical modeling and regression/ANOVA analysis.
- **Key Features**:
  - Perform regression analysis to understand relationships between variables.
  - Tools for hypothesis testing and advanced statistical models.
  
**Example**:
```python
import statsmodels.api as sm
X = [1, 2, 3, 4]  # Predictor variable
y = [2, 4, 6, 8]  # Response variable
model = sm.OLS(y, sm.add_constant(X)).fit()
print(model.summary())
```

---

## Geopandas
- **Purpose**: Geospatial data analysis for location-specific datasets.
- **Key Features**:
  - Read and process spatial data formats like shapefiles.
  - Perform spatial joins, intersections, and buffers.
  - Create maps for data visualization.

**Example**:
```python
import geopandas as gpd
gdf = gpd.read_file("your_shapefile.shp")
print(gdf.head())  # Displays the first few rows of spatial data
```

---

# Summary
These libraries are essential for any data analysis workflow:
- **Pandas**: Tabular data manipulation.
- **Numpy**: Numerical calculations.
- **Seaborn & Matplotlib**: Data visualization.
- **Statsmodels**: Statistical modeling.
- **Geopandas**: Geospatial data analysis.

Feel free to copy and paste this into a Jupyter Notebook! Just for now!!! ðŸ˜Š

In [ ]:
import pandas as pd

# Read a CSV file
df = pd.read_csv("sample_data.csv") # if you have the data downloaded local and you need to read it 
print(df.head())  # Display the first 5 rows

# Get basic stats
print(df["column_name"].mean())
print(df["column_name"].unique())

In [ ]:
# https://support.socrata.com/hc/en-us/articles/202949268-How-to-query-more-than-1000-rows-of-a-dataset
import pandas as pd

# URL of the dataset (Traffic Collisions in NYC)
url = "https://data.cityofnewyork.us/resource/h9gi-nx95.csv"

# Set a limit for the number of records to fetch (use $limit parameter)
record_limit = 50  # Adjust the limit as needed 

# Append the $limit parameter to the URL
query_url = f"{url}?$limit={record_limit}"

# Read the dataset using Pandas
print(f"Fetching data from: {query_url}")
try:
    df = pd.read_csv(query_url)
    print("Dataset successfully loaded!")

    # Display the first 5 rows of the dataset
    print("First 5 rows of the dataset:")
    print(df.head())

    # Display basic information about the dataset
    print("\nDataset Info:")
    print(df.info())

except Exception as e:
    print("An error occurred while fetching the dataset:", e)

Fetching data from: https://data.cityofnewyork.us/resource/h9gi-nx95.csv?$limit=50
Dataset successfully loaded!
First 5 rows of the dataset:
                crash_date crash_time   borough  zip_code  latitude  \
0  2021-09-11T00:00:00.000       2:39       NaN       NaN       NaN
1  2022-03-26T00:00:00.000      11:45       NaN       NaN       NaN
2  2023-11-01T00:00:00.000       1:29  BROOKLYN   11230.0  40.62179
3  2022-06-29T00:00:00.000       6:55       NaN       NaN       NaN
4  2022-09-21T00:00:00.000      13:21       NaN       NaN       NaN

   longitude                       location           on_street_name  \
0        NaN                            NaN    WHITESTONE EXPRESSWAY
1        NaN                            NaN  QUEENSBORO BRIDGE UPPER
2 -73.970024  \n,  \n(40.62179, -73.970024)            OCEAN PARKWAY
3        NaN                            NaN       THROGS NECK BRIDGE
4        NaN                            NaN          BROOKLYN BRIDGE

  off_street_name cross_street_name  ...  contributing_factor_vehicle_2  \
0       20 AVENUE               NaN  ...                    Unspecified
1             NaN               NaN  ...                            NaN
2        AVENUE K               NaN  ...                    Unspecified
3             NaN               NaN  ...                    Unspecified
4             NaN               NaN  ...                    Unspecified

   contributing_factor_vehicle_3  contributing_factor_vehicle_4  \
0                            NaN                            NaN
1                            NaN                            NaN
2                    Unspecified                            NaN
3                            NaN                            NaN
4                            NaN                            NaN

   contributing_factor_vehicle_5  collision_id  \
0                            NaN       4455765
1                            NaN       4513547
2                            NaN       4675373
3                            NaN       4541903
4                            NaN       4566131

                    vehicle_type_code1  vehicle_type_code2  \
0                                Sedan               Sedan
1                                Sedan                 NaN
2                                Moped               Sedan
3                                Sedan       Pick-up Truck
4  Station Wagon/Sport Utility Vehicle                 NaN

   vehicle_type_code_3 vehicle_type_code_4 vehicle_type_code_5
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                Sedan                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN

[5 rows x 29 columns]

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_date                     50 non-null     object
 1   crash_time                     50 non-null     object
 2   borough                        23 non-null     object
 3   zip_code                       23 non-null     float64
 4   latitude                       29 non-null     float64
 5   longitude                      29 non-null     float64
 6   location                       29 non-null     object
 7   on_street_name                 37 non-null     object
 8   off_street_name                19 non-null     object
 9   cross_street_name              13 non-null     object
 10  number_of_persons_injured      50 non-null     int64
 11  number_of_persons_killed       50 non-null     int64
 12  number_of_pedestrians_injured  50 non-null     int64
 13  number_of_pedestrians_killed   50 non-null     int64
 14  number_of_cyclist_injured      50 non-null     int64
 15  number_of_cyclist_killed       50 non-null     int64
 16  number_of_motorist_injured     50 non-null     int64
 17  number_of_motorist_killed      50 non-null     int64
 18  contributing_factor_vehicle_1  49 non-null     object
 19  contributing_factor_vehicle_2  36 non-null     object
 20  contributing_factor_vehicle_3  2 non-null      object
 21  contributing_factor_vehicle_4  0 non-null      float64
 22  contributing_factor_vehicle_5  0 non-null      float64
 23  collision_id                   50 non-null     int64
 24  vehicle_type_code1             48 non-null     object
 25  vehicle_type_code2             26 non-null     object
 26  vehicle_type_code_3            2 non-null      object
 27  vehicle_type_code_4            0 non-null      float64
 28  vehicle_type_code_5            0 non-null      float64
dtypes: float64(7), int64(9), object(13)
memory usage: 11.5+ KB
None